# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VechileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_photo', models.ImageField(upload_to='media/pic/')),
                ('V_file', models.FileField(upload_to='media/file/')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
