# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vechilemodel',
            name='V_accomadate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vechilemodel',
            name='V_model',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vechilemodel',
            name='V_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vechilemodel',
            name='V_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
