# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_vechilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechilemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
