# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_registermodel_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='user',
            new_name='email',
        ),
    ]
