# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181012_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registermodel',
            old_name='user',
            new_name='email',
        ),
    ]
